Add pan events
revery-ui/reason-sdl2 pull request #25
Opened 2019-10-30 19:01 UTC by szbergeron

WIP: plumbs support for smooth scrolling

Adds a new "MousePan" event type that matches up with https://github.com/revery-ui/esy-sdl2/pull/6

Needs to be integrated with Revery proper before it will work

2019-10-30 19:14 UTC, szbergeron commented
Builds probably failing due to missing symbols (relies on changes in esy-sdl2#6)

2019-11-21 22:19 UTC, bryphe commented on src/sdl2_wrapper.cpp
> +  printf("event type is %d while pan event type is %d and mousewheel is %d\n", event->type, SDL_PANEVENT, SDL_MOUSEWHEEL);
We should remove the `printf`s for the final version

2019-11-23 16:29 UTC, Et7f3 commented on src/sdl2_wrapper.cpp
> +      printf("Unknown event in sdl2_wrapper, event enum code was %d\n", event->type);
```suggestion
      fprintf(stderr, "Unknown event in sdl2_wrapper, event enum code was %d\n", event->type);
```

2019-11-26 01:51 UTC, Et7f3 approved these changes

2019-12-06 01:24 UTC, bryphe commented
I think if you bring in the latest master, this should be build now @szbergeron 👍

2019-12-06 01:25 UTC, bryphe commented on src/sdl2_wrapper.cpp
> +      fprintf(stderr, "Unknown event in sdl2_wrapper, event enum code was %d\n", event->type);
We should remove this as well - might cause issues in the case where we run on Windows w/o a console allocated (we could hook into the `SDL_Log` mechanism though instead)

2019-12-06 01:25 UTC, bryphe requested changes
One minor change - we should remove the `fprintf`. Otherwise, everything else looks good - it should build now w/ `master` merged

2019-12-06 22:15 UTC, bryphe commented
Looks great, @szbergeron ! Thank you!

2019-12-06 22:15 UTC, merged